spring:
  application:
    name: kafka_UItool
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: test
